version: '3.5'

services:
  backend:
    hostname: rehearsals-backend
    container_name: rehearsal-backend
    network_mode: host
    image: docker.pkg.github.com/rehearsalsbooking/backend/backend:latest
    volumes:
      - .env.backend:/app/.env
      - ./logs:/app/storage/logs
    depends_on:
      - db
    environment:
      - DB_HOST=localhost

  db:
    image: postgres:alpine
    hostname: db
    network_mode: host
    environment:
      - POSTGRES_DB=rehearsals
      - POSTGRES_USER=rehearsals
      - POSTGRES_PASSWORD=rehearsals
    ports:
      - 5432:5432

  frontend:
    build:
      context: ../
      dockerfile: dev/Dockerfile
    ports:
      - 8080:8080
    network_mode: host
    volumes:
      - ../:/app
    depends_on:
      - backend