name: Release

on:
  workflow_dispatch:

env:
  IMAGE_NAME: "frontend"

jobs:
  release-prod:
    environment:
      name: production
      url: https://festic.ru

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-prod
          key: ${{ runner.os }}-buildx-prod-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-prod-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: PrepareReg Names
        run: |
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Build and export
        uses: docker/build-push-action@v2
        env:
          VUE_APP_ENV: "production"
        with:
          file: docker/production/Dockerfile
          tags: |
            ghcr.io/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:production
            ghcr.io/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:production-${{ github.event.inputs.version }}
          cache-from: type=local,src=/tmp/.buildx-cache-prod
          cache-to: type=local,dest=/tmp/.buildx-cache-prod-new,mode=max
          push: true
          builder: ${{ steps.buildx.outputs.name }}

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-prod
          mv /tmp/.buildx-cache-prod-new /tmp/.buildx-cache-prod

  release-demo:
    environment:
      name: demo
      url: https://demo.festic.ru

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-demo
          key: ${{ runner.os }}-buildx-demo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-demo-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: PrepareReg Names
        run: |
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Build and export
        uses: docker/build-push-action@v2
        env:
          VUE_APP_ENV: "demo"
        with:
          file: docker/demo/Dockerfile
          tags: |
            ghcr.io/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:demo
          cache-from: type=local,src=/tmp/.buildx-cache-demo
          cache-to: type=local,dest=/tmp/.buildx-cache-demo-new,mode=max
          push: true
          builder: ${{ steps.buildx.outputs.name }}

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-demo
          mv /tmp/.buildx-cache-demo-new /tmp/.buildx-cache-demo